In [39]:
using DelimitedFiles, Random, Statistics, LinearAlgebra
using Distributions, Plots, LaTeXStrings
include("/workspaces/proposed/pilotConsistent/gendat.jl")
include("/workspaces/proposed/pilotConsistent/estimators.jl")

using DelimitedFiles

In [3]:
# Read csv file
X = readdlm("/workspaces/proposed/X.csv", ',', Float64, '\n')

664×75 Matrix{Float64}:
  0.0655348    0.33161    -0.144391   …  -0.0122357   -0.185506   -0.0389523
  0.110648    -0.0462351   0.207961      -0.169898     0.0246838  -0.0358784
  0.0568006   -0.0278991   0.132631      -0.0998821    0.0283107  -0.0216497
  0.0398977   -0.0138945  -0.0355425      0.0123803   -0.189949   -0.0398852
 -0.0163595   -0.0132565  -0.0823464      0.126283    -0.0720386   0.352256
  0.0625028   -0.046812    0.183797   …  -0.150418    -0.130979   -0.0418825
  0.101465    -0.0538128   0.140998      -0.131533     0.154051   -0.0417587
  0.00931615  -0.0236581  -0.085691       0.188275    -0.107402   -0.0455554
  0.0577751   -0.0537857   0.145518      -0.15817     -0.120328   -0.0417377
  0.0577041   -0.0142555  -0.0779488     -0.15054     -0.149654   -0.0445666
  0.113913     0.170972   -0.169649   …  -0.220649     0.0320572  -0.0465957
  0.170162     0.407621   -0.0767137     -0.0128107    0.198915   -0.0407828
  0.0400185    0.0439677  -0.063237       0.121878   

In [55]:
Y = readdlm("/workspaces/proposed/Y.csv", ',', Float64, '\n')

# Convert Y to Vector of Bool
Y = vec(convert(Array{Bool}, Y))
Y

664-element Vector{Bool}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 ⋮
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0

In [56]:
nss = [100]
n0 = 1

1

In [57]:
fitbeta = estBetas(X, Y, nss, n0)


H is singular


LoadError: SingularException(74)

In [50]:
(X_sim, Y_sim) = gendat(1000, 3, [-7; -ones(6)]);

In [51]:
Y_sim

1000-element Vector{Bool}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 ⋮
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0